spring.application.name=EmpSphere-NK

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

server.port=1677

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true